name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      
    - name: Type check
      run: npm run typecheck
      env:
        VITE_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Lint
      run: npm run lint
      env:
        VITE_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Build
      run: npm run build
      env:
        VITE_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Test
      run: npm run test
      env:
        VITE_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}